- name: Add apt packages
  apt:
    name: python3-sh
    update_cache: true
    cache_valid_time: 3600
    state: present

- name: Add pip packages
  pip:
    name: prometheus_client
    state: present

- name: Add /usr/local/bin/barman_exporter file
  copy:
    src: barman_exporter.py
    dest: /usr/local/bin/barman_exporter
    owner: root
    group: root
    mode: 0755
  notify: restart barman-exporter

- name: Add /etc/systemd/system/barman-exporter.service file
  template:
    src: barman-exporter.service.j2
    dest: /etc/systemd/system/barman-exporter.service
    owner: root
    group: root
    mode: 0644
  register: __barman_exporter_systemd
  notify: restart barman-exporter

- meta: flush_handlers

- name: Start barman-exporter service
  systemd:
    name: barman-exporter
    enabled: true
    state: started

- name: Check if service is running
  command: >
    /bin/systemctl is-active barman-exporter
  changed_when: false
